### ISSUE TITLE
Synchronization 'on save' causes entire IDE to hang

### ISSUE THREAD

**Issue by kalosh007** [syllant/idea-plugin-remotesynchronizer#18]
When I update the java file and hit ctrl+s, I see synchronizing in the RemoteSynchronizer console and entire IDE hangs. The same can be achieved by hitting 'Synchronize all' function.
TaskManager shows 33% of CPU usage and IDE is not responsive.
IDEA 14.1.2
System: WIN8.1 64bit.
Project: 30 modules, around 5400 java files.

**Comment by kalosh007** [comment]
Hello.
I am posting the log here as this issue is more relevant. I can't attach the file here, so I am pasting. Sorry.
2015-06-08 08:48:21,692 [3122390]   INFO - j.compiler.server.BuildManager - Using preloaded build process to compile C:\src 
2015-06-08 08:48:26,404 [3127102]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /C:/Program Files (x86)/JetBrains/IntelliJ IDEA Community Edition 14.1.2/lib/jps-launcher.jar;C:/Program Files/Java/jdk1.7.0_45/lib/tools.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA Community Edition 14.1.2/lib/optimizedFileManager.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA Community Edition 14.1.2/lib/ecj-4.4.jar 
2015-06-08 08:48:54,899 [3155597]   INFO - agnostic.FrequentEventDetector - Too many events posted
java.lang.Throwable
	at com.intellij.openapi.diagnostic.FrequentEventDetector.eventHappened(FrequentEventDetector.java:61)
	at com.intellij.ide.IdeEventQueue.postEvent(IdeEventQueue.java:1029)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1257)
	at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1290)
	at org.sylfra.idea.plugins.remotesynchronizer.ui.ThreadConsole.append(ThreadConsole.java:206)
	at org.sylfra.idea.plugins.remotesynchronizer.ui.ThreadConsole.append(ThreadConsole.java:201)
	at org.sylfra.idea.plugins.remotesynchronizer.ui.ThreadConsole.fileCopying(ThreadConsole.java:357)
	at org.sylfra.idea.plugins.remotesynchronizer.synchronizing.SynchronizerThread.copyFile(SynchronizerThread.java:389)
	at org.sylfra.idea.plugins.remotesynchronizer.synchronizing.SynchronizerThread.synchronize(SynchronizerThread.java:204)
	at org.sylfra.idea.plugins.remotesynchronizer.synchronizing.SynchronizerThread.access$000(SynchronizerThread.java:33)
	at org.sylfra.idea.plugins.remotesynchronizer.synchronizing.SynchronizerThread$1$1.run(SynchronizerThread.java:181)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at org.sylfra.idea.plugins.remotesynchronizer.synchronizing.SynchronizerThread$1.run(SynchronizerThread.java:177)
 
2015-06-08 08:49:47,110 [3207808]   INFO - ellij.concurrency.JobScheduler - 50 ms execution limit failed for: com.intellij.openapi.progress.impl.CoreProgressManager$1@106c5b0; elapsed time was 110ms 
2015-06-08 08:56:50,945 [3631643]   INFO - lij.tasks.impl.TaskManagerImpl - Updating issues cache (every 20 min) 
2015-06-08 09:00:23,276 [3843974]   INFO - j.compiler.server.BuildManager - Using preloaded build process to compile C:\src 
2015-06-08 09:00:28,087 [3848785]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: C:\src\fujitsu-bss\Development\fujitsu-adm-um-portal\javasrc\com\fujitsu\adm\um\ui\dialog\mp\subscriptions\SubscriptionsCtrl.java:63: error: unmappable character for encoding UTF-8 
2015-06-08 09:00:28,087 [3848785]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: System.out.println("G?wno."); 
2015-06-08 09:00:28,087 [3848785]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: ^ 
2015-06-08 09:00:38,642 [3859340]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /C:/Program Files (x86)/JetBrains/IntelliJ IDEA Community Edition 14.1.2/lib/jps-launcher.jar;C:/Program Files/Java/jdk1.7.0_45/lib/tools.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA Community Edition 14.1.2/lib/optimizedFileManager.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA Community Edition 14.1.2/lib/ecj-4.4.jar 
2015-06-08 09:01:13,763 [3894461]   INFO - r.impl.FileDocumentManagerImpl - reload server.log from disk? 
2015-06-08 09:01:13,763 [3894461]   INFO - r.impl.FileDocumentManagerImpl -   documentStamp:20148 
2015-06-08 09:01:13,764 [3894462]   INFO - r.impl.FileDocumentManagerImpl -   oldFileStamp:13194 
2015-06-08 09:01:15,170 [3895868]  ERROR - .impl.MessageBusConnectionImpl - null 
java.lang.NullPointerException
	at org.sylfra.idea.plugins.remotesynchronizer.actions.RemoteSynchronizeAllAction.getFiles(RemoteSynchronizeAllAction.java:16)
	at org.sylfra.idea.plugins.remotesynchronizer.actions.AbstractRemoteSynchronizeAction.actionPerformed(AbstractRemoteSynchronizeAction.java:27)
	at org.sylfra.idea.plugins.remotesynchronizer.utils.ConfigStateComponent$1.beforeDocumentSaving(ConfigStateComponent.java:51)
	at sun.reflect.GeneratedMethodAccessor336.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
	at com.sun.proxy.$Proxy19.beforeDocumentSaving(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor336.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:138)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:87)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:116)
	at com.sun.proxy.$Proxy19.beforeDocumentSaving(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$4.run(FileDocumentManagerImpl.java:422)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:354)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:419)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocument(FileDocumentManagerImpl.java:393)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:314)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:293)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1373)
	at com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.java:27)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-06-08 09:01:15,172 [3895870]  ERROR - .impl.MessageBusConnectionImpl - IntelliJ IDEA 14.1.2  Build #IC-141.713.2 
2015-06-08 09:01:15,172 [3895870]  ERROR - .impl.MessageBusConnectionImpl - JDK: 1.8.0_40 
2015-06-08 09:01:15,172 [3895870]  ERROR - .impl.MessageBusConnectionImpl - VM: Java HotSpot(TM) Server VM 
2015-06-08 09:01:15,172 [3895870]  ERROR - .impl.MessageBusConnectionImpl - Vendor: Oracle Corporation 
2015-06-08 09:01:15,172 [3895870]  ERROR - .impl.MessageBusConnectionImpl - OS: Windows 8 
2015-06-08 09:01:15,172 [3895870]  ERROR - .impl.MessageBusConnectionImpl - Last Action: SaveAll 
2015-06-08 09:01:25,726 [3906424]   INFO - ateSettings.impl.UpdateChecker - Connection failed (connect timed out). Please check network connection and try again.

**Comment by kalosh007** [comment]
I have found a reason, why IDE hangs. I have almost 6000 class files and the syncronization takes a lot of time. Is it possible to synchronize .class files only for those *.java which were saved?

**Comment by danmana** [comment]
I'm having a similar problem, but in may case I'm only copying a few js/css files
1 file copied, 13 files ignored => 2-3 second hang of the ide

What I noticed is that if "synchronize on save" is checked the ide hangs, but if I trigger the sync all by hand the ide doesn't hang (it still takes a few seconds to sync the files, even if I have just a couple)

**Comment by syllant** [comment]
Interesting. 2 things to investigate for me:
* why "Synchronize All" would be OK when "Synchronize on Save" is not
* if I can only synchronize saved files for "Synchronize on Save"

Can't commit on any date to fix, but definitively the highest priority. Thanks for the reports.

Sylvain

**Comment by syllant** [comment]
Should be fixed in the 1.11 version. Actually synchronization was launched against the whole project for each changed file!

@kalosh007 @danmana Any feedback would be appreciated to confirm the fix.

**Comment by danmana** [comment]
@syllant thanks for the very fast fix
It works perfectly, now "Synchronize on Save" doesn't lock up the UI and only checks the saved files, which is fast :)

**Comment by syllant** [comment]
Cool, thanks for confirming!
